language: python
python:
- '3.5'
- '3.6'
cache: pip
before_install:
- wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O
  miniconda.sh
- export MINICONDA_PREFIX="$HOME/miniconda"
- bash miniconda.sh -b -p $MINICONDA_PREFIX
- export PATH="$MINICONDA_PREFIX/bin:$PATH"
- conda config --set always_yes yes
- conda update -q conda
- conda config --add channels bioconda
- conda config --add channels conda-forge
- conda info -a
install:
- conda create -n test-env pytest pytest-cov coveralls networkx>=2 fastspar>=0.0.7 pandas numpy scipy biom-format pandas
  scikit-bio statsmodels h5py pytest-runner tqdm matplotlib seaborn
- source activate test-env
- conda list
- pip install --no-cache-dir --editable .
script:
- export MPLBACKEND=Agg
- py.test --cov SCNIC --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: michael.shaffer
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: shafferm/SCNIC
  password:
    secure: QEK8nsJtOJo2lvpVSxCX54gscFks5OCHGARbrY1KGGihvTMAyOr9wTqcnKnz6B2Zdvrz2XMKss4FaBlfo9izKCkCtALz/6QrlpgL2H2twYwDtUSVJ8rDw5j0k2JOiX6qyuklMmGTkbTXH3lEl5SNDmUtU1DUA1YUJfr/urC7BMmR6k8QZdb6/mPWEIOUG2bzcZsSxtk3Cj5o30b3OFR4Fmpt5K0L/SxYa0VBSzKfjhS/BId7X2fQtdFtVAAfqpAdE3NSGcMPgRNT3JAv4Nqei1ePzObrsEn7diOtTPusVJlDt/DEE7oTsJUi5ZedpeHCeahBLeDjaLS8unkORlU9QAjHVbN4ibMGonDaivgwDE1xHn4pRV3QVLup3Qsru/U6C+KInT3QjrEeSgLsz+HL4SmZN0wx+x6ZnkjxufzEJKxq5p/z1Ai/fci+OiVUOFdXYIqxhlsaeAPI5ky2W74zFvVC89w2bpVvFR+wqhX6z0HfeDfK6qp8hYWOmWoogyBSBqxDo9mkejgnBRKQLgtteT9kHiU5CnXlOnvvBOqCbUfQXQ2R7gKU8lTliWV9vExD+Ni6mVpWdTrfk5bcqicdMC9mdSDmdpb+p4YxHsrOHcLlYgn1ElT8Ok/vqmINP6vyD+lsGWAwxJVRokFC902rhPCzp0Fr4rIzXKl6hGQCVOE=
